[package]
name = "penumbra-c-bindings"
version = "0.1.0"
edition = "2021"
crate-type = [ "staticlib" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penumbra-view = { path = "../view" }

[build-dependencies]
cbindgen = "0.24.3"